---
image: node

stages:
  - test
  - release

test:
  stage: test
  script:
    - echo 'Make your tests here !'
  except:
    - master
  tags:
    - sib

publish:
  stage: release
  before_script:
    - npm install -g semantic-release@v16.0.0-beta.18 @semantic-release/gitlab
    - npm install -D
    - git checkout $CI_COMMIT_REF_NAME
  script:
    - npm run build:prod
    - semantic-release
  only:
    - master
  tags:
    - sib
