---
include:
  project: infra/gitlab
  ref: master
  file: templates/nodejs.ci.yml

default:
  image: node:16

# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress

stages:
  - test
  - prepare
  - publish

test:
  image: cypress/base:14
  stage: test
  before_script:
    - node -v
    - npm -v
    - npm ci --cache .npm --prefer-offline
    - npm list
  script:
    - export NODE_OPTIONS=--max_old_space_size=4096
    - npm run check-types
    - npm run build
    - npm test
  except:
    - master
    - tags
  tags:
    - test

prepare:
  stage: prepare
  image: node:14
  before_script:
    - npm ci --cache .npm --prefer-offline
    - npm install -g semantic-release@v17.1 @semantic-release/gitlab@6.0.5
  script:
    - npm run build
  artifacts:
    when: on_success
    paths:
      - dist
    expire_in: 1 day
  tags:
    - test

publish:
  stage: publish
  extends: .publish_npm
  only:
    - master
    - beta
