---
include:
  project: infra/gitlab
  ref: master
  file: templates/nodejs.ci.yml

default:
  image: node:18

# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress

stages:
  - prepare
  - test
  - publish

test:
  image: cypress/base:18.16.0
  stage: test
  before_script:
    - npm ci
  script:
    - npm run check-types
    - npm run build
    - npm test
  except:
    - master
    - tags
  tags:
    - test

prepare:
  stage: prepare
  image: node:18
  before_script:
    - npm cache clean -f
    - npm ci --force --cache .npm --prefer-offline
    - npm install -g semantic-release@v17.1 @semantic-release/gitlab@6.0.5
  script:
    - npm run build
  artifacts:
    when: on_success
    paths:
      - dist
    expire_in: 1 day
  tags:
    - test
    - publish

publish:
  stage: publish
  extends: .publish_npm
  only:
    - master
    - beta

