---
image: node:12

stages:
  - test
  - release

test:
  stage: test
  before_script:
    - npm install -D
  script:
    - npm run test
  except:
    - master
    - tags
  tags:
    - test

publish:
  stage: release
  before_script:
    - npm install -g semantic-release@v17 @semantic-release/gitlab
    - npm install
  script:
    - npm run build:prod
    - semantic-release
  only:
    - master
    - beta
  tags:
    - deploy
