---
image: node:12

# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress

stages:
  - test
  - release

test:
  image: cypress/base:10
  stage: test
  before_script:
    - npm ci
  script:
    - npm run check-types
    - npm run build
    - npm test
  except:
    - master
    - tags
  artifacts:
    paths:
      - cypress/videos
      - cypress/screenshots
    expire_in: 1 day
  tags:
    - test

publish:
  stage: release
  before_script:
    - npm install -g semantic-release@v17 @semantic-release/gitlab
    - npm install
  script:
    - npm run build:prod
    - semantic-release
  only:
    - master
    - beta
  tags:
    - deploy
